In [3]:
%%capture
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)

In [22]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#AGEMC

- ASK
- GET
- EXPLORER
- Análise exploratória
- Análise explanatória
- MODEL
- COMMUNICATE

In [ ]:
# Machine learning não é um processo de bibliotecas, mas antes, um processo de pensamento humano onde começamos com problemas
# e temos mais papel e caneta do que código. é Como a Cole Knaflic disse qualquer um é capaz de gerar um visualização, é tão fácil
# gerar gráficos hoje que as pessoas quase não pensam antes de cria-los.

# Pergunta: Sobre as paradas polícias em NewYork

In [ ]:
import pandas as pd

# Leitura com UTF-8 (padrão para a maioria dos arquivos modernos)
df_utf8 = pd.read_csv('seu_arquivo.csv', encoding='utf-8')

# Leitura com Latin-1 (muito comum em sistemas legados do Windows e exportações do Excel)
df_latin1 = pd.read_csv('seu_arquivo.csv', encoding='latin-1')

# Nota: 'iso-8859-1' é equivalente ao 'latin-1' no contexto do pandas
df_iso = pd.read_csv('seu_arquivo.csv', encoding='iso-8859-1')

In [9]:
df = pd.read_csv("/content/export (2).csv", encoding= 'latin-1')

In [10]:
df.to_csv('df_NYPD_paradas_policiais.csv', index= False)

In [11]:
df = pd.read_csv('/content/df_NYPD_paradas_policiais.csv')

In [12]:
df.head()

,EVNT_KEY,OCCUR_DT,OCCUR_TM,CMD_CD,VEH_SEIZED_FLG,VEH_SEARCHED_FLG,VEH_SEARCH_CONSENT_FLG,VEH_CHECKPOINT_FLG,FORCE_USED_FLG,ARREST_MADE_FLG,SUMMON_ISSUED_FLG,VEH_CATEGORY,RPTED_AGE,SEX_CD,RACE_DESC,LATITUDE,LONGITUDE,X_COORD_CD,Y_COORD_CD
0,327335539,06/30/2026,00:03:00,43,False,False,(null),False,False,False,False,CAR/SUV,49,M,BLACK,0.0,0.0,1026884.0,239400.0
1,327394110,06/30/2026,20:05:00,42,False,False,(null),True,False,False,False,CAR/SUV,28,M,HISPANIC,0.0,0.0,1012422.0,240916.0
2,327377398,06/30/2026,15:10:32,123,False,False,(null),False,False,False,True,CAR/SUV,41,F,HISPANIC,0.0,0.0,914725.0,125836.0
3,327377397,06/30/2026,15:04:00,123,False,False,(null),False,False,False,True,CAR/SUV,37,F,WHITE,0.0,0.0,914725.0,125836.0
4,327394111,06/30/2026,20:08:00,42,False,False,(null),True,False,False,False,CAR/SUV,32,F,HISPANIC,0.0,0.0,1012422.0,240916.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2971075 entries, 0 to 2971074
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   EVNT_KEY                int64
 1   OCCUR_DT                object
 2   OCCUR_TM                object
 3   CMD_CD                  int64
 4   VEH_SEIZED_FLG          bool
 5   VEH_SEARCHED_FLG        bool
 6   VEH_SEARCH_CONSENT_FLG  object
 7   VEH_CHECKPOINT_FLG      bool
 8   FORCE_USED_FLG          bool
 9   ARREST_MADE_FLG         bool
 10  SUMMON_ISSUED_FLG       bool
 11  VEH_CATEGORY            object
 12  RPTED_AGE               object
 13  SEX_CD                  object
 14  RACE_DESC               object
 15  LATITUDE                float64
 16  LONGITUDE               float64
 17  X_COORD_CD              float64
 18  Y_COORD_CD              float64
dtypes: bool(6), float64(4), int64(2), object(7)
memory usage: 311.7+ MB

In [14]:
df.describe()

,EVNT_KEY,CMD_CD,LATITUDE,LONGITUDE,X_COORD_CD,Y_COORD_CD
count,2.971075e+06,2.971075e+06,2.769270e+06,2.769270e+06,2.968453e+06,2.968453e+06
mean,2.964364e+08,6.935827e+01,3.397750e+01,-6.167631e+01,1.005673e+06,2.031026e+05
std,1.898799e+07,3.543273e+01,1.514105e+01,2.748395e+01,2.542885e+04,3.092123e+04
min,2.611820e+08,1.000000e+00,0.000000e+00,-7.425232e+01,-7.400000e+01,4.000000e+01
25%,2.812147e+08,4.300000e+01,4.061483e+01,-7.396343e+01,9.913140e+05,1.809310e+05
50%,2.974635e+08,7.000000e+01,4.069547e+01,-7.390809e+01,1.004637e+06,2.016810e+05
75%,3.133608e+08,1.050000e+02,4.076465e+01,-7.380279e+01,1.020718e+06,2.287910e+05
max,3.280414e+08,1.230000e+02,4.091260e+01,0.000000e+00,1.067220e+06,2.717770e+05

In [16]:
df.columns

Index(['EVNT_KEY', 'OCCUR_DT', 'OCCUR_TM', 'CMD_CD', 'VEH_SEIZED_FLG',
       'VEH_SEARCHED_FLG', 'VEH_SEARCH_CONSENT_FLG', 'VEH_CHECKPOINT_FLG',
       'FORCE_USED_FLG', 'ARREST_MADE_FLG', 'SUMMON_ISSUED_FLG',
       'VEH_CATEGORY', 'RPTED_AGE', 'SEX_CD', 'RACE_DESC', 'LATITUDE',
       'LONGITUDE', 'X_COORD_CD', 'Y_COORD_CD'],
      dtype='object')

In [18]:
# Sobre a Raça das pessoas

df.RACE_DESC.value_counts().reset_index()

                        RACE_DESC   count
0                           BLACK  887886
1                        HISPANIC  854804
2                           WHITE  563724
3        ASIAN / PACIFIC ISLANDER  385738
4                         UNKNOWN  228513
5  AMERICAN INDIAN/ALASKAN NATIVE   41583
6                           OTHER    8826
7                          (null)       1

In [28]:
plt.figure(figsize= (12, 5))

df.RACE_DESC.hist()

# plt.plot([1, 2], [2, 4])

AttributeError: 'Series' object has no attribute 'histbar'